[window]
dynamic_title = false
opacity = 0.6
title = "Alacritty"
dimensions = { columns = 80, lines = 24 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.0

[colors]
[colors.primary]
background = "#1f2129"
foreground = "#ffffff"
